#服务配置
server:
  port: 9003
#spring配置
spring:
  #1.应用配置
  application:
    name: platform-rcmd #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true

web.upload-path: C:\Users\SYC\Desktop\project-saas-hrm-vue-master